version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw deploy

workflows:
  build-then-test:
    jobs:
      - build
